version: '3'

services:
  strapi:
    image: taktart/strapi-app:latest
    build: .
    ports:
      - '1337:1337'
    environment:
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: ./data/data.db
    volumes:
      - ./data:/srv/app/data
    restart: always
