name: Deploy Strapi to ARM Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for ARM
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm64 -t taktart/strapi-arm:latest --push .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH into ARM Server and deploy Strapi
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_IP }}
          username: ${{ secrets.HETZNER_USER }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            docker pull taktart/strapi-arm:latest
            docker stop strapi || true
            docker rm strapi || true
            docker run -d --name strapi -p 1337:1337 taktart/strapi-arm:latest
