name: Deploy Strapi to ARM Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for ARM
        run: |
          docker buildx create --use
          docker buildx build \
          --build-arg DATABASE_CLIENT=sqlite \
          --build-arg DATABASE_FILENAME=.tmp/data.db \
          --build-arg HOST=${{ secrets.HOST }} \
          --build-arg PORT=${{ secrets.PORT }} \
          --build-arg NODE_ENV=production \
          --build-arg ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }} \
          --build-arg API_TOKEN_SALT=${{ secrets.API_TOKEN_SALT }} \
          --build-arg APP_KEYS=${{ secrets.APP_KEYS }} \
          --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
          --build-arg TRANSFER_TOKEN_SALT=${{ secrets.TRANSFER_TOKEN_SALT }} \
          --build-arg ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }} \
          --platform linux/arm64 -t taktart/strapi-arm:latest \
          --push .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH into ARM Server and deploy Strapi
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_IP }}
          username: ${{ secrets.HETZNER_USER }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            docker system prune -af
            docker pull taktart/strapi-arm:latest
            docker stop strapi || true
            docker rm strapi || true
            docker volume create strapi-sqlite-data
            docker volume create strapi-media
            docker run -d \
            -e DATABASE_CLIENT=sqlite \
            -e DATABASE_FILENAME=.tmp/data.db \
            -e HOST=${{ secrets.HOST }} \
            -e PORT=${{ secrets.PORT }} \
            -e ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }} \
            -e API_TOKEN_SALT=${{ secrets.API_TOKEN_SALT }} \
            -e APP_KEYS=${{ secrets.APP_KEYS }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e TRANSFER_TOKEN_SALT=${{ secrets.TRANSFER_TOKEN_SALT }} \
            -e ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }} \
            -e NODE_ENV=production \
            -v strapi-sqlite-data:/srv/app/.tmp \
            -v strapi-media:/srv/app/public/uploads \
            -p 1337:1337 \
            --name strapi \
            taktart/strapi-arm:latest
